# https://github.com/googleapis/release-please?tab=readme-ov-file#how-should-i-write-my-commits
name: "convention"

on:
  pull_request_target:
    branches: [main]
    types: [opened, edited]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  title:
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: read
    steps:
      - uses: amannn/action-semantic-pull-request@677b89571e961351de6fcbd96c8b2503787962e2 # v5.5.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
